dist: xenial
language: generic
addons:
  apt:
    packages:
      - python-gi
      - gir1.2-gtk-3.0
      - python-lxml
      - python-matplotlib
      - python-tornado
      - python-cairo
      - python3-setuptools
      - python3-gi
      - python3-lxml
      - python3-cairo
      - python3-gi-cairo
      - python3-matplotlib
services:
  - mysql
env:
  - PYTHON_VERSION=2.7 PYTRAINER_ALCHEMYURL="sqlite://"
  - PYTHON_VERSION=3.5 PYTRAINER_ALCHEMYURL="sqlite://"
  - PYTHON_VERSION=2.7 PYTRAINER_ALCHEMYURL="mysql://pytrainer@localhost/pytrainer"
  - PYTHON_VERSION=3.5 PYTRAINER_ALCHEMYURL="mysql://pytrainer@localhost/pytrainer"
before_install:
  - mysql -e "CREATE USER 'pytrainer'@'localhost';"
  - mysql -e "CREATE DATABASE pytrainer;"
  - mysql -e "GRANT ALL PRIVILEGES ON pytrainer . * TO 'pytrainer'@'localhost';"
script: "TZ=Europe/Kaliningrad xvfb-run python$PYTHON_VERSION -Wall setup.py test"
notifications:
  irc:
    channels: "ircs://chat.freenode.net:7000/#pytrainer"
